// WebSocket
export const WEBSOCKET_CONNECTION_REQUEST: "WEBSOCKET_CONNECTION_REQUEST" =
  "WEBSOCKET_CONNECTION_REQUEST";
export const WEBSOCKET_CONNECTION_SUCCESS: "WEBSOCKET_CONNECTION_SUCCESS" =
  "WEBSOCKET_CONNECTION_SUCCESS";
export const WEBSOCKET_CONNECTION_FAILED: "WEBSOCKET_CONNECTION_FAILED" =
  "WEBSOCKET_CONNECTION_FAILED";
export const WEBSOCKET_CONNECTION_CLOSED: "WEBSOCKET_CONNECTION_CLOSED" =
  "WEBSOCKET_CONNECTION_CLOSED";
export const WEBSOCKET_GET_ORDERS: "WEBSOCKET_GET_ORDERS" =
  "WEBSOCKET_GET_ORDERS";

// Ingredients
export const FETCH_INGREDIENTS_REQUEST: "FETCH_INGREDIENTS_REQUEST" =
  "FETCH_INGREDIENTS_REQUEST";
export const FETCH_INGREDIENTS_SUCCESS: "FETCH_INGREDIENTS_SUCCESS" =
  "FETCH_INGREDIENTS_SUCCESS";
export const FETCH_INGREDIENTS_ERROR: "FETCH_INGREDIENTS_ERROR" =
  "FETCH_INGREDIENTS_ERROR";

export const INCREASE_INGREDIENT_COUNT: "INCREASE_INGREDIENT_COUNT" =
  "INCREASE_INGREDIENT_COUNT";
export const DECREASE_INGREDIENT_COUNT: "DECREASE_INGREDIENT_COUNT" =
  "DECREASE_INGREDIENT_COUNT";

// Constructor
export const ADD_BUN_TO_CONSTRUCTOR: "ADD_BUN_TO_CONSTRUCTOR" =
  "ADD_BUN_TO_CONSTRUCTOR";
export const DELETE_BUN_FROM_CONSTRUCTOR: "DELETE_BUN_FROM_CONSTRUCTOR" =
  "DELETE_BUN_FROM_CONSTRUCTOR";
export const ADD_MAIN_TO_CONSTRUCTOR: "ADD_MAIN_TO_CONSTRUCTOR" =
  "ADD_MAIN_TO_CONSTRUCTOR";
export const DELETE_MAIN_FROM_CONSTRUCTOR: "DELETE_MAIN_FROM_CONSTRUCTOR" =
  "DELETE_MAIN_FROM_CONSTRUCTOR";
export const SET_NEW_ORDER_OF_MAINS: "SET_NEW_ORDER_OF_MAINS" =
  "SET_NEW_ORDER_OF_MAINS";

// Order
export const CREATE_ORDER_LOADING: "CREATE_ORDER_LOADING" =
  "CREATE_ORDER_LOADING";
export const CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS" =
  "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED: "CREATE_ORDER_FAILED" = "CREATE_ORDER_FAILED";

// User
export const GET_USER_LOADING: "GET_USER_LOADING" = "GET_USER_LOADING";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";

export const REGISTER_USER_LOADING: "REGISTER_USER_LOADING" =
  "REGISTER_USER_LOADING";
export const REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS" =
  "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED: "REGISTER_USER_FAILED" =
  "REGISTER_USER_FAILED";

export const LOGIN_USER_LOADING: "LOGIN_USER_LOADING" = "LOGIN_USER_LOADING";
export const LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS" = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED: "LOGIN_USER_FAILED" = "LOGIN_USER_FAILED";

export const LOGOUT_USER_LOADING: "LOGOUT_USER_LOADING" = "LOGOUT_USER_LOADING";
export const LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS" = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILED: "LOGOUT_USER_FAILED" = "LOGOUT_USER_FAILED";

export const UPDATE_USER_LOADING: "UPDATE_USER_LOADING" = "UPDATE_USER_LOADING";
export const UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS" = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED: "UPDATE_USER_FAILED" = "UPDATE_USER_FAILED";

export const FORGOT_PASSWORD_LOADING: "FORGOT_PASSWORD_LOADING" =
  "FORGOT_PASSWORD_LOADING";
export const FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS" =
  "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED: "FORGOT_PASSWORD_FAILED" =
  "FORGOT_PASSWORD_FAILED";

export const RESTORE_PASSWORD_LOADING: "RESTORE_PASSWORD_LOADING" =
  "RESTORE_PASSWORD_LOADING";
export const RESTORE_PASSWORD_SUCCESS: "RESTORE_PASSWORD_SUCCESS" =
  "RESTORE_PASSWORD_SUCCESS";
export const RESTORE_PASSWORD_FAILED: "RESTORE_PASSWORD_FAILED" =
  "RESTORE_PASSWORD_FAILED";

export const CHECK_AUTHORISATION: "CHECK_AUTHORISATION" = "CHECK_AUTHORISATION";
